"""empty message

Revision ID: 791f4aa0026c
Revises: 581651e88387
Create Date: 2023-03-31 16:23:46.294681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791f4aa0026c'
down_revision = '581651e88387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('add_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('add_user', schema=None) as batch_op:
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###
