"""empty message

Revision ID: 984e31a63ad2
Revises: 
Create Date: 2023-03-30 23:09:19.282114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984e31a63ad2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('add_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fav_color', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('add_user', schema=None) as batch_op:
        batch_op.drop_column('fav_color')

    # ### end Alembic commands ###
